run:
  timeout: 5m
  tests: true
  skip-dirs:
    - test/fixtures

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - "test/fixtures/.*"
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  govet:
    enable:
      - shadow

output:
  formats:
    - format: colored-line-number
