run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - test/fixtures
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-rules:
    - path: test/
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

output:
  formats:
    - format: colored-line-number
